### ISSUE TITLE
[BUG] Installed all dependencies but still got an error: AttributeError: module 'glib' has no attribute 'get_user_config_dir'

### ISSUE THREAD

**Issue by Elizabeth819** [Azure-Samples/graphrag-accelerator#107]
**Describe the bug**
When deploy.sh, got an error: 
Deploying graphrag helm chart... cosmos endpoint: [https://cosmos-eliz3.documents.azure.com:443/](https://cosmos-eliz3.documents.azure.com/)
storage account url: https://steliz3.blob.core.windows.net/
Traceback (most recent call last):
  File "/Users/wanmeng/miniconda3/envs/graphrag/bin/helm", line 42, in <module>
    main()
  File "/Users/wanmeng/miniconda3/envs/graphrag/bin/helm", line 28, in main
    config_dirs = (glib.get_user_config_dir(),) + glib.get_system_config_dirs()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'glib' has no attribute 'get_user_config_dir'

**To Reproduce**
1. install all the dependencies
2. bash deploy.sh -d -g -p deploy.parameters.json
3. get the error
**Expected behavior**

**Screenshots**
<img width="851" alt="image" src="https://github.com/user-attachments/assets/4ed04c2c-2c91-44f4-b309-7e340876c026">
<img width="613" alt="image" src="https://github.com/user-attachments/assets/fffe6879-5642-4d2a-a6dd-a3e051572cc0">
![image](https://github.com/user-attachments/assets/33d0efc6-ead7-4b52-aa9c-2c21fd9fb0f3)
![image](https://github.com/user-attachments/assets/8a8e9dfe-504c-4788-a187-adde1df48542)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]

**Additional context**

**Comment by rnpramasamyai** [comment]
@Elizabeth819
Please make sure that you have installed the necessary tools.
