### ISSUE TITLE
[BUG] Frontend app fails to start due to ModuleNotFoundError: No module named 'altair.vegalite.v4'

### ISSUE THREAD

**Issue by timothymeyers** [Azure-Samples/graphrag-accelerator#175]
**Describe the bug**
After the recently merged PR, the Frontend app no longer can start due to the below error.

**To Reproduce**

1. Build frontend container via provided Dockerfile
2. Deploy to Azure Container App
3. Hit endpoint

(This used to work last week)

**Screenshots**

```bash
2024-09-18T13:04:04.41573  Successfully Connected to container: 'graphrag-frontend'
Traceback (most recent call last):
  File "/usr/local/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/usr/local/lib/python3.10/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/usr/local/lib/python3.10/site-packages/streamlit/delta_generator.py", line 43, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/usr/local/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py", line 36, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'
```

**Comment by timothymeyers** [comment]
@jgbradley1 I know you're working on an update to the frontend app, but wanted to make sure you were aware of this.
