### ISSUE TITLE
[BUG] Running frontend streamlit app results in TypeError

### ISSUE THREAD

**Issue by timothymeyers** [Azure-Samples/graphrag-accelerator#20]
Following the frontend/README.md instructions, running the streamlit app results in

```
2024-06-26 13:11:07.202 Uncaught app exception
Traceback (most recent call last):
  File "/graphrag-accelerator/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/graphrag-accelerator/frontend/app.py", line 589, in <module>
    asyncio.run(app())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/graphrag-accelerator/frontend/app.py", line 135, in app
    st.session_state["entity_config"] = ["DEFAULT"] + get_entity_data(api_url)[
TypeError: 'NoneType' object is not subscriptable
```

**Comment by americanthinker** [comment]
Streamlit frontend is completed as of July 5.  Waiting on final testing (Monday July 8) before merging into `main`.

**Comment by jgbradley1** [comment]
@timothymeyers @americanthinker the frontend has been added back and tested with the latest API endpoints.

Will close this issue for now but open up a new one if any new problems show up.
